# Generated by Django 5.2.16 on 2026-07-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['created_at'], 'verbose_name': 'مقال', 'verbose_name_plural': 'المقالات'},
        ),
    ]
